name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload To Pgyer
      run: curl -S "http://www.pgyer.com/apiv2/app/upload" -F "file=@app/build/outputs/apk/debug/app-debug.apk" -F "_api_key=${{ secrets.pgyer_api_key }}"
